config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  resources :posts
  resources :users
  get 'users', to: 'users#show'

  get 'api/v1/posts/:id', to: 'posts#show'
  get 'api/v1/posts', to: 'posts#index'
  post 'api/v1/posts', to: 'posts#create'

  post 'api/v1/reports/by_author', to: 'posts#report_by_author'

  get 'raffle' => 'raffle#index'

  get 'basket' => 'basket#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  validates :nickname,  presence: true
  validates :email,     presence: true
  #validates :password,  presence: true
  validates :password, length: {minimum: 5, maximum: 120}, on: :update, allow_blank: true

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController


  def index

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to user_path current_user.id
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# its dangerous option, but I use it once to avoid difficult authenticate system
skip_before_filter :verify_authenticity_token
  def index
    @posts = Post.all.order(published_at: :desc)
    respond_to do |format|
      format.json { render json: @posts }
      response.headers['Posts-count'] = @posts.count.to_s
      #еще требовалось количество страниц передавать - но непонтяно что за величина такая
    end
  end


  def show
    @post = Post.find params[:id]
    respond_to do |format|
      format.json { render json: @post }
    end
  end


  def create
    @post = Post.new
    @post.title = params[:title]
    @post.body = params[:body]
  #поскольку поле author_id связано с аутентификацией (которой нет), пока делаем его устанавливаемым вручную, через параметр
    @post.author_id = params[:author_id]
    if params[:published_at].nil?
      @post.published_at = DateTime.now
    else
      @post.published_at = params[:published_at]
    end
    if @post.save
      respond_to do |format|
        format.json { render json: @post }
      end
    else
      respond_to do |format|
        format.json { render json: @post.errors.messages }
      end
    end
  end



  def report_by_author
    #сделать бэкгроаундный отчет с отправкой по имейлу
    Resque.enqueue(Resqueee, params)
    #binding.pry
    respond_to do |format|
      format.json { render json: @posts }
    end
    #Resque.enqueue(Resqueee, params)


    #ReportMailer.report_delivering(output_array).deliver_now
  end

  def get_nick_by_id user_id
    User.find(user_id).nickname
  end

  def get_email_by_id user_id
    User.find(user_id).email
  end


#  private
#  def post_params
#    params.require(:post).permit(:title, :body, :author_id, :published_at)
#  end

end

app/controllers/raffle_controller.rb
class RaffleController < ApplicationController


  def index

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'rmagick'
  include Magick

  def show
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.save

    img = Magick::Image.read(params[:user][:avatar].tempfile.path).first
    #binding.pry
    ilist = Magick::ImageList.new
    mark = Magick::Image.new(img.columns, img.rows)

    gc = Magick::Draw.new
    gc.gravity = Magick::CenterGravity
    gc.pointsize = 32
    gc.font_family = "Helvetica"
    gc.font_weight = Magick::BoldWeight
    gc.stroke = 'none'
    gc.annotate(mark, 0, 0, 0, 0, params[:watermark])


    ilist << mark.shade(true)
    img.composite!(ilist, Magick::CenterGravity, Magick::HardLightCompositeOp)

    img.write 'public/rm_out.png' # save rm picture
    user.avatar = Rails.root.join("public/rm_out.png").open   # use rm picture as uploaded
    #binding.pry
    user.save

    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/raffle_helper.rb
module RaffleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Juntest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header_menu' %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class = "row"> <%= post.title %> </div>
  <div> <%= post.body %> </div>
<% end %>

app/views/raffle/index.html.erb
<h1> Raffler </h1>

<!--<div ng-controller="RaffleCtrl"> -->
<div ng-controller="RaffleCtrl">
  <div >
    <form>
      <input type="text" ng-model="newEntry.name">
    </form>

{{ newEntry.name }}
  </div>
</div>

app/views/shared/_header_menu.html.erb
<nav class="nav navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "home", posts_path %>
    </div>

    <ul class="nav navbar-nav pull-right ">
      <li ><%= link_to "api_v1_posts", api_v1_posts_path(:json), :method => 'get' %></li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id) %>
        <li ><%= link_to "Выйти", destroy_user_session_path, :method => 'delete', id: "aquit" %></li>
      <% else %>
        <li ><%= link_to "Войти", new_user_session_path, :method => 'create' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
user <%= @user.nickname %>
<br>
<%# binding.pry %>
<%= image_tag(@user.avatar) %>

<% if @user == current_user %>
  <%= form_for @user, html: { multiupart: true } do |f| %>
    <%= f.file_field :avatar, {class: 'file_input', onchange: "pressed()"} %>
    <%= text_field_tag :watermark, nil, :placeholder=>'текст водного знака'  %>
    <%= f.submit 'Сохранить аватар', { :method => 'get', id: 'btn-upload', class: 'btn btn-sm' } %>
  <% end %>
<% end %>
<br>
<img class="hiddendiv" id="preview" src="#" alt="your image" />